# Generated by Django 3.2.6 on 2021-09-18 19:45

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_pic',
            field=models.ImageField(default='nopic.jpg', upload_to=posts.models.Post.generate_cover_pic_path),
        ),
    ]
