# Generated by Django 3.2.6 on 2021-09-25 05:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_cover_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_manager_name': 'query'},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
